name: "Fairlee drive-in movies"
description: "Know when the Fairlee, VT drive-in movie theater changes their movies."
version: "1.0.0"
slug: "fairlee_drive_in"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386